/*
 * FlowrouteNumbersAndMessaging.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using FlowrouteNumbersAndMessaging.Standard;
using FlowrouteNumbersAndMessaging.Standard.Utilities;


namespace FlowrouteNumbersAndMessaging.Standard.Models
{
    public class Attributes28 : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string malias;
        private bool? cnamLookupsEnabled;
        private Models.NumberTypeEnum? numberType;
        private string rateCenter;
        private string state;
        private int? mvalue;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("alias")]
        public string Alias 
        { 
            get 
            {
                return this.malias; 
            } 
            set 
            {
                this.malias = value;
                onPropertyChanged("Alias");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cnam_lookups_enabled")]
        public bool? CnamLookupsEnabled 
        { 
            get 
            {
                return this.cnamLookupsEnabled; 
            } 
            set 
            {
                this.cnamLookupsEnabled = value;
                onPropertyChanged("CnamLookupsEnabled");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("number_type", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.NumberTypeEnum? NumberType 
        { 
            get 
            {
                return this.numberType; 
            } 
            set 
            {
                this.numberType = value;
                onPropertyChanged("NumberType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("rate_center")]
        public string RateCenter 
        { 
            get 
            {
                return this.rateCenter; 
            } 
            set 
            {
                this.rateCenter = value;
                onPropertyChanged("RateCenter");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("state")]
        public string State 
        { 
            get 
            {
                return this.state; 
            } 
            set 
            {
                this.state = value;
                onPropertyChanged("State");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("value")]
        public int? Value 
        { 
            get 
            {
                return this.mvalue; 
            } 
            set 
            {
                this.mvalue = value;
                onPropertyChanged("Value");
            }
        }
    }
} 