/*
 * FlowrouteNumbersAndMessaging.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace FlowrouteNumbersAndMessaging.Standard.Models
{
    public class Attributes : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string amountDisplay;
        private double? amountNanodollars;
        private string body;
        private List<Models.DeliveryReceipt> deliveryReceipts;
        private string direction;
        private string mfrom;
        private bool? isMms;
        private int? messageEncoding;
        private Models.MessageTypeEnum? messageType;
        private string status;
        private DateTime? timestamp;
        private string to;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("amount_display")]
        public string AmountDisplay 
        { 
            get 
            {
                return this.amountDisplay; 
            } 
            set 
            {
                this.amountDisplay = value;
                onPropertyChanged("AmountDisplay");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("amount_nanodollars")]
        public double? AmountNanodollars 
        { 
            get 
            {
                return this.amountNanodollars; 
            } 
            set 
            {
                this.amountNanodollars = value;
                onPropertyChanged("AmountNanodollars");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("body")]
        public string Body 
        { 
            get 
            {
                return this.body; 
            } 
            set 
            {
                this.body = value;
                onPropertyChanged("Body");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("delivery_receipts")]
        public List<Models.DeliveryReceipt> DeliveryReceipts 
        { 
            get 
            {
                return this.deliveryReceipts; 
            } 
            set 
            {
                this.deliveryReceipts = value;
                onPropertyChanged("DeliveryReceipts");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("direction")]
        public string Direction 
        { 
            get 
            {
                return this.direction; 
            } 
            set 
            {
                this.direction = value;
                onPropertyChanged("Direction");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("from")]
        public string From 
        { 
            get 
            {
                return this.mfrom; 
            } 
            set 
            {
                this.mfrom = value;
                onPropertyChanged("From");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("is_mms")]
        public bool? IsMms 
        { 
            get 
            {
                return this.isMms; 
            } 
            set 
            {
                this.isMms = value;
                onPropertyChanged("IsMms");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("message_encoding")]
        public int? MessageEncoding 
        { 
            get 
            {
                return this.messageEncoding; 
            } 
            set 
            {
                this.messageEncoding = value;
                onPropertyChanged("MessageEncoding");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("message_type", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.MessageTypeEnum? MessageType 
        { 
            get 
            {
                return this.messageType; 
            } 
            set 
            {
                this.messageType = value;
                onPropertyChanged("MessageType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("status")]
        public string Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("timestamp")]
        public DateTime? Timestamp 
        { 
            get 
            {
                return this.timestamp; 
            } 
            set 
            {
                this.timestamp = value;
                onPropertyChanged("Timestamp");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("to")]
        public string To 
        { 
            get 
            {
                return this.to; 
            } 
            set 
            {
                this.to = value;
                onPropertyChanged("To");
            }
        }
    }
} 