/*
 * FlowrouteNumbersAndMessaging.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using Newtonsoft.Json;


namespace FlowrouteNumbersAndMessaging.Standard.Models
{
    public class Data27 : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.Attributes28 attributes = new Models.Attributes28();
        private string id;
        private Models.Links links = new Models.Links();
        private object relationships;
        private string type = "number";

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("attributes")]
        public Models.Attributes28 Attributes 
        { 
            get 
            {
                return this.attributes; 
            } 
            set 
            {
                this.attributes = value;
                onPropertyChanged("Attributes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("links")]
        public Models.Links Links 
        { 
            get 
            {
                return this.links; 
            } 
            set 
            {
                this.links = value;
                onPropertyChanged("Links");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("relationships")]
        public object Relationships 
        { 
            get 
            {
                return this.relationships; 
            } 
            set 
            {
                this.relationships = value;
                onPropertyChanged("Relationships");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("type")]
        public string Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }
    }
} 