/*
 * FlowrouteNumbersAndMessaging.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using FlowrouteNumbersAndMessaging.Standard;
using FlowrouteNumbersAndMessaging.Standard.Utilities;


namespace FlowrouteNumbersAndMessaging.Standard.Models
{
    public class DeliveryReceipt : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int? level;
        private string status;
        private int? statusCode;
        private string statusCodeDescription;
        private DateTime? timestamp;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("level")]
        public int? Level 
        { 
            get 
            {
                return this.level; 
            } 
            set 
            {
                this.level = value;
                onPropertyChanged("Level");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("status")]
        public string Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("status_code")]
        public int? StatusCode 
        { 
            get 
            {
                return this.statusCode; 
            } 
            set 
            {
                this.statusCode = value;
                onPropertyChanged("StatusCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("status_code_description")]
        public string StatusCodeDescription 
        { 
            get 
            {
                return this.statusCodeDescription; 
            } 
            set 
            {
                this.statusCodeDescription = value;
                onPropertyChanged("StatusCodeDescription");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("timestamp")]
        public DateTime? Timestamp 
        { 
            get 
            {
                return this.timestamp; 
            } 
            set 
            {
                this.timestamp = value;
                onPropertyChanged("Timestamp");
            }
        }
    }
} 