/*
 * FlowrouteNumbersAndMessaging.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using FlowrouteNumbersAndMessaging.Standard;
using FlowrouteNumbersAndMessaging.Standard.Utilities;


namespace FlowrouteNumbersAndMessaging.Standard.Models
{
    public class Links : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string self;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("self")]
        public string Self 
        { 
            get 
            {
                return this.self; 
            } 
            set 
            {
                this.self = value;
                onPropertyChanged("Self");
            }
        }
    }
} 