/*
 * FlowrouteNumbersAndMessaging.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using Newtonsoft.Json;


namespace FlowrouteNumbersAndMessaging.Standard.Models
{
    public class Links : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string self;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("self")]
        public string Self 
        { 
            get 
            {
                return this.self; 
            } 
            set 
            {
                this.self = value;
                onPropertyChanged("Self");
            }
        }
    }
} 