/*
 * FlowrouteNumbersAndMessaging.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using Newtonsoft.Json;


namespace FlowrouteNumbersAndMessaging.Standard.Models
{
    public class Number26 : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.Data27 data = new Models.Data27();
        private object included;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("data")]
        public Models.Data27 Data 
        { 
            get 
            {
                return this.data; 
            } 
            set 
            {
                this.data = value;
                onPropertyChanged("Data");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("included")]
        public object Included 
        { 
            get 
            {
                return this.included; 
            } 
            set 
            {
                this.included = value;
                onPropertyChanged("Included");
            }
        }
    }
} 