/*
 * FlowrouteNumbersAndMessaging.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using FlowrouteNumbersAndMessaging.Standard;
using FlowrouteNumbersAndMessaging.Standard.Utilities;

namespace FlowrouteNumbersAndMessaging.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum RouteTypeEnum
    {
        SIPREG, //TODO: Write general description for this method
        HOST, //TODO: Write general description for this method
        URI, //TODO: Write general description for this method
        NUMBER, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type RouteTypeEnum
    /// </summary>
    public static class RouteTypeEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "sip-reg", "host", "uri", "number" };

        /// <summary>
        /// Converts a RouteTypeEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The RouteTypeEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(RouteTypeEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case RouteTypeEnum.SIPREG:
                case RouteTypeEnum.HOST:
                case RouteTypeEnum.URI:
                case RouteTypeEnum.NUMBER:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of RouteTypeEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of RouteTypeEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<RouteTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into RouteTypeEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed RouteTypeEnum value</returns>
        public static RouteTypeEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type RouteTypeEnum", value));

            return (RouteTypeEnum) index;
        }
    }
} 